config/routes.rb
Myorder::Application.routes.draw do
  devise_for :users

  resources :markers

  resources :restaurants

  resources :menus

  resources :orders
  
  match "api/order" => "api#add_order"
  match "api/end_order/:id" => "api#end_order"
  
  match "map" => "orders#map"
  match "stats" => "orders#stats"
  
  root :to => "orders#index"

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :marker
  belongs_to :menu
  
  validates :marker_id, :menu_order, :presence => true
  
  before_create :attach_status
  
  def attach_status
    self.status = 'open'
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_filter :authenticate_user!
  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.where("status" => 'open')
    
    @orders.each do |order|
      order.menu_order = ActiveSupport::JSON.decode(order.menu_order)
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @orders }
    end
  end
  
  def map
    orders = Order.where("status" => 'open')
    
    @data = {}
    orders.each do |order|
      @data[order.marker_id.to_s] = true
    end
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @orders }
    end
  end
  
  def stats
    @data = {}
    inv = InventoryLog.find(:all, :conditions => {:ref_date => Date.today - 7..Date.today}, :order => "ref_date ASC")
    inv.each do |l|
      @data[l.ref_date.to_s] = {"inv" => l.amount.to_s}
    end
    
    sale = SaleLog.find(:all, :conditions => {:ref_date => Date.today - 7..Date.today}, :order => "ref_date ASC")
    sum = 0;
    date = sale.first.ref_date.to_s;
    sale.each do |l|
      if date == l.ref_date.to_s
        sum += l.amount
      else
        @data[date] = {"sale" => sum}
        sum = 0
        date = l.ref_date.to_s
      end
    end
    
    if sum != 0
      @data[date].merge!({"sale" => sum})
    end
    
    puts @data.inspect
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @orders }
    end
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @order = Order.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/new
  # GET /orders/new.json
  def new
    @order = Order.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/1/edit
  def edit
    @order = Order.find(params[:id])
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(params[:order])

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render json: @order, status: :created, location: @order }
      else
        format.html { render action: "new" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /orders/1
  # PUT /orders/1.json
  def update
    @order = Order.find(params[:id])

    respond_to do |format|
      if @order.update_attributes(params[:order])
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order = Order.find(params[:id])
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :ok }
    end
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
  def calculate_price(items)
    sum = 0;
    items.each do |i|
      item = Menu.find(i['menu_id'])
      sum += item.price * i['quantity']
    end
    sum
  end
end

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :marker_id %><br />
    <%= f.number_field :marker_id %>
  </div>
  <div class="field">
    <%= f.label :menu_id %><br />
    <%= f.number_field :menu_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<h2>Customer Orders</h2>

<script type="text/javascript">
$(document).ready(function() {
  $('.ui-slider').each(function(i, e) {
    $(e).bind('touchend mouseup', function() { 
      check_list($(this));
    });
  });
});

function check_list(item) {
  var id = item.parent().parent().attr('data-id');
  item.parent().parent().remove();
  $.post('/api/end_order/' + id, function(data) {
  });
}
</script>

<ul id="order_list" data-role="listview" data-inset="true">
<% @orders.each do |order| %>
  <li class="ui-li ui-li-static ui-body-c ui-corner-none" data-id="<%= order.id %>">
    <div style="float:right">
      <select name="slider2" id="slider2" class="close_order_button" data-role="slider">
        <option value="off">Open</option>
        <option value="on">Done</option>
      </select>
    </div>
    <p class="ui-li-aside ui-li-desc" style="float: left">
      <h3>
      <% order.menu_order.each do |menu| %>
        <% menu_item = Menu.find(menu['menu_id']) %>
        <%= menu_item.name %>: <%= menu['quantity'] %>
      <% end %>
      </h3>
    </p>
    <p>Total price: $<%= calculate_price(order.menu_order) %></p>
  </li>
<% end %>
</ul>

app/views/orders/map.html.erb
<h2>Order Map</h2>

<div id="map_container">
  <%= image_tag('map.png') %>
  <% @data.each do |ind, dat| %>
  <% mark = "<p id='mark" + ind.to_s + "'>" + ind.to_s + "</p>" %>
  <%= mark.html_safe %>
  <% end %>
</div>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Marker:</b>
  <%= @order.marker_id %>
</p>

<p>
  <b>Menu:</b>
  <%= @order.menu_id %>
</p>


<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/orders/stats.html.erb
<h2>Inventory Stats</h2>

<div id="inventory" style="width: 800px; height: 300px; margin: auto">
</div>

<script type="text/javascript">

$(document).ready(function() {
  Morris.Line({
    element: 'inventory',
    data: [
    <% @data.each do |index, val| %>
      <% sale = val['sale'].nil? ? 0 : val['sale'] %>
      <% inv = val['inv'].nil? ? 0 : val['inv'] %>
      <%= "{y: '" + index + "', a: " + inv.to_s + ", b: " + sale.to_s + "}," %>
    <% end %>
    ],
    xkey: 'y',
    ykeys: ['a', 'b'],
    labels: ['Inventory', 'Sales'],
    smooth: false,
    hideHover: true
  });
});

</script>